<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('sale-pages/index') }}">{{ trans('sale-page-management') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('sale-pages/index') }}">{{ trans('sale-page-management') }}</a>
            <small>
                <i class="icon-double-angle-right"></i>
                {% if salePages is not empty %}
                    {{ trans('label.edit') }}
                {% else %}
                    {{ trans('label.add') }}
                {% endif %}
            </small>
        </h1>
    </div>
    <form action="{{url('sale-pages/publish')}}" method="post" class="form-horizontal" id="save-archive-form" enctype="multipart/form-data">
        <div class="col-lg-12">
            <h3 class="header smaller lighter blue">{{ trans('label.information') }}</h3>
            <div class="form-group">
                <label for="archive-title" class="col-sm-2 control-label">{{ trans('label.title') }}</label>
                <div class="col-sm-9">
                    <input type="name" name="name" class="form-control" id="name" {% if salePages is not empty %}value="{{salePages['name']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-alias" class="col-sm-2 control-label">{{ trans('label.alias') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="alias" class="form-control" id="alias" {% if salePages is not empty %}value="{{salePages['alias']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-category" class="col-sm-2 control-label">{{ trans('label.category') }}</label>
                <div class="col-sm-4">
                    <div class="archive-category-list">
                        <ul>
                            {% for value in categoryList %}
                            <li>
                            <div class="checkbox">
                                <label>
                                <input type="checkbox" name="category[]" value="{{value['id']}}"
                                    {% if salePages['categories'] is not empty %}
                                       {% for cv in salePages['categories'] %}
                                            {% if cv['id'] == value['id'] %}
                                                checked="checked"
                                                {% break %}
                                            {% endif %}
                                       {% endfor %}
                                    {% endif %}
                                />{{value['name']}}
                                </label>
                            </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-keyword" class="col-sm-2 control-label">{{ trans('label.keyword') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="keyword" class="form-control" id="keyword" {% if salePages is not empty %}value="{{salePages['keyword']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-phone" class="col-sm-2 control-label">{{ trans('label.phone') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="phone" class="form-control" id="phone" {% if salePages is not empty %}value="{{salePages['phone']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-email" class="col-sm-2 control-label">{{ trans('label.email') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="email" class="form-control" id="email" {% if salePages is not empty %}value="{{salePages['email']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="address" class="col-sm-2 control-label">{{ trans('label.address') }}</label>
                <div class="col-sm-9">
                    <textarea id="address" name="address" class="autosize-transition form-control">{% if salePages is not empty %}{{salePages['address']}}{% endif %}</textarea>
                </div>
            </div>

            <h3 class="header smaller lighter blue">{{ trans('label.content') }}</h3>

            <div class="form-group">
                <label for="upimage" class="col-sm-2 control-label">{{ trans('label.image') }}</label>
                <div class="col-sm-9 has-success">
                    <input id="upimage" name="upimage" type="file" />
                    <div class="help-block col-xs-12 col-sm-reset">
                        File size max: 2MB, Size: 1500x1000 (px)
                    </div>
                </div>
            </div>
            {% if salePages['image'] is not empty %}
            <div class="form-group">
                <div class="col-sm-9 col-sm-offset-2">
                    <span class="profile-picture">
                        <img class="editable img-responsive editable-click editable-empty" src="{{salePages['image']}}" />
                    </span>
                </div>
            </div>
            {% endif %}
            <div class="form-group">
                <label for="uplogo" class="col-sm-2 control-label">{{ trans('label.logo') }}</label>
                <div class="col-sm-9 has-success">
                    <input id="uplogo" name="uplogo" type="file" />
                    <div class="help-block col-xs-12 col-sm-reset">
                        File size max: 2MB, Size: 500x500 (px)
                    </div>
                </div>
            </div>
            {% if salePages['logo'] is not empty %}
            <div class="form-group">
                <div class="col-sm-9 col-sm-offset-2">
                    <span class="profile-picture">
                        <img class="editable img-responsive editable-click editable-empty" src="{{salePages['logo']}}" />
                    </span>
                </div>
            </div>
            {% endif %}
            <div class="form-group">
                <label for="description" class="col-sm-2 control-label">{{ trans('label.description') }}</label>
                <div class="col-sm-9">
                    <textarea id="description" name="description" class="autosize-transition form-control">{% if salePages is not empty %}{{salePages['description']}}{% endif %}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="content" class="col-sm-2 control-label">{{ trans('label.content') }}</label>
                <div class="col-sm-9">
                    <textarea id="content" class="tinymce autosize-transition form-control" name="content">{% if salePages is not empty %}{{salePages['content']}}{% endif %}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="video" class="col-sm-2 control-label">{{ trans('label.video') }}</label>
                <div class="col-sm-9">
                    <textarea id="video" name="video" class="autosize-transition form-control">{% if salePages is not empty %}{{salePages['video']}}{% endif %}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="archive-name" class="col-sm-2 control-label">{{ trans('label.status') }}</label>
                <div class="controls col-xs-12 col-sm-9">
                    <div class="row">
                        <div class="col-xs-3">
                            <label>
                                <input name="status" class="ace ace-switch ace-switch-4 btn-flat" type="checkbox" value="1" {% if salePages is not empty and salePages['status'] == 1 %}checked="checked"{% endif %} />
                                <span class="lbl"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <h3 class="header smaller lighter blue">{{ trans('label.popup') }}</h3>
            
            <div class="form-group">
                <label for="uppopup_image" class="col-sm-2 control-label">{{ trans('label.popup_image') }}</label>
                <div class="col-sm-9 has-success">
                    <input id="uppopup_image" name="uppopup_image" type="file" />
                    <div class="help-block col-xs-12 col-sm-reset">
                        File size max: 2MB, Size: 750x500 (px)
                    </div>
                </div>
            </div>
            {% if salePages is not empty %}
            <div class="form-group">
                <div class="col-sm-9 col-sm-offset-2">
                    <span class="profile-picture">
                        <img class="editable img-responsive editable-click editable-empty" src="{{salePages['popup_image']}}" />
                    </span>
                </div>
            </div>
            {% endif %}
            <div class="form-group">
                <label for="popup_tracking" class="col-sm-2 control-label">{{ trans('label.tracking-id') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="popup_tracking" class="form-control" id="popup_tracking" {% if salePages is not empty %}value="{{salePages['popup_tracking']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="popup_description" class="col-sm-2 control-label">{{ trans('label.popup_description') }}</label>
                <div class="col-sm-9">
                    <textarea id="popup_description" class="tinymce autosize-transition form-control" name="popup_description">{% if salePages is not empty %}{{salePages['popup_description']}}{% endif %}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="is_popup" class="col-sm-2 control-label">{{ trans('label.is_popup') }}</label>
                <div class="controls col-xs-12 col-sm-9">
                    <div class="row">
                        <div class="col-xs-3">
                            <label>
                                <input name="is_popup" class="ace ace-switch ace-switch-4 btn-flat" type="checkbox" value="1" {% if salePages is not empty and salePages['is_popup'] == 1 %}checked="checked"{% endif %} />
                                <span class="lbl"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <h3 class="header smaller lighter blue">{{ trans('label.footer') }}</h3>
            
            <div class="form-group">
                <label for="copyright" class="col-sm-2 control-label">{{ trans('label.copyright') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="copyright" class="form-control" id="copyright" {% if salePages is not empty %}value="{{salePages['copyright']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="link_facebook" class="col-sm-2 control-label">{{ trans('label.link_facebook') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="link_facebook" class="form-control" id="link_facebook" {% if salePages is not empty %}value="{{salePages['link_facebook']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="link_google" class="col-sm-2 control-label">{{ trans('label.link_google') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="link_google" class="form-control" id="link_google" {% if salePages is not empty %}value="{{salePages['link_google']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="link_twitter" class="col-sm-2 control-label">{{ trans('label.link_twitter') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="link_twitter" class="form-control" id="link_twitter" {% if salePages is not empty %}value="{{salePages['link_twitter']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="link_linkedin" class="col-sm-2 control-label">{{ trans('label.link_linkedin') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="link_linkedin" class="form-control" id="link_linkedin" {% if salePages is not empty %}value="{{salePages['link_linkedin']}}"{% endif %}>
                </div>
            </div>
            <div class="form-group">
                <label for="link_youtube" class="col-sm-2 control-label">{{ trans('label.link_youtube') }}</label>
                <div class="col-sm-9">
                    <input type="text" name="link_youtube" class="form-control" id="link_youtube" {% if salePages is not empty %}value="{{salePages['link_youtube']}}"{% endif %}>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    {% if salePages is not empty %}
                        <input type="hidden" name="id" value="{{salePages['id']}}" />
                    {% endif %}
                    <button type="button" class="btn btn-info btn-sm" data-status="1" id="save-sale-pages-btn">{{ trans('label.save') }}</button>
                    <button type="button" class="btn btn-sm" data-status="2" id="save-sale-pages-draft-btn">{{ trans('label.save-draft') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>
<link rel="stylesheet" href="{{ static_url('tagsinput/jquery.tagsinput.css?_v=')~assetsVersion }}" />
<script src="{{ static_url('tagsinput/jquery.tagsinput.js?_v=')~assetsVersion }}"></script>
<script>
    $('#archive-tags').tagsInput({
        'defaultText':'',
        'width':'100%',
        'height':'auto'
    });
    $('#save-sale-pages-btn, #save-sale-pages-draft-btn').on('click', function(){
        var title = $.trim($('#name').val());
        if(typeof title == 'undefined' || title == false){
            tips_message("{{ trans('label.title') }}");
            return false;
        }

        var category = new Array();
        $('input[name="category[]"]').each(function(){
            if($(this).is(':checked')){
                category.push($(this).val());
            }
        });
        if(category.length == 0){
            tips_message('{{ trans('alert.select-category') }}');
            return false;
        }

        var status = $(this).attr('data-status');
        $('#status').val(status);

        $('#save-archive-form').submit();
    });
    
</script>