<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('forms_submit/forms_submit') }}">{{ trans('forms_submit') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('categorys/index') }}">{{ trans('forms_submit') }}</a>
            <small>
                <i class="icon-double-angle-right"></i>
                {{ trans('info-change') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#forms_submit" data-toggle="tab">{{ trans('forms_submit') }}</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" id="forms_submit">
                <form action="{{url('forms-submit/publish')}}" method="post" class="form-horizontal" id="save-forms_submit-form">
                    <div class="form-group">
                        <label for="fullname" class="col-sm-2 control-label">{{ trans('label.fullname') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['fullname']}}" {% endif %} class="form-control" id="fullname" name="fullname">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">{{ trans('label.email') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['email']}}" {% endif %} class="form-control" id="email" name="email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone" class="col-sm-2 control-label">{{ trans('label.phone') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['phone']}}" readonly="" {% endif %} class="form-control" id="phone" name="phone">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="address" class="col-sm-2 control-label">{{ trans('label.address') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['address']}}" readonly="" {% endif %} class="form-control" id="address" name="address">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ trans('label.link') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['link']}}" readonly="" {% endif %} class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ trans('label.browser') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['browser']}}" readonly="" {% endif %} class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ trans('label.ip') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['ip']}}" readonly="" {% endif %} class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ trans('label.device') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if formsSubmit is not empty %}value="{{formsSubmit['device']}}" readonly="" {% endif %} class="form-control">
                        </div>
                    </div>

                    {% if formsSubmit['plus'] is not empty %}
                        {% for item in formsSubmit['plus'] %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ item['key'] }}</label>
                                <div class="col-sm-5">
                                    <input type="text" {% if item['value'] is not empty %}value="{{ item['value'] }}" readonly="" {% endif %} class="form-control">
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <!-- <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-5">
                            <input type="hidden" {% if formsSubmit.id is not empty %} value="{{formsSubmit.id}}" {% endif %} class="form-contro   l" name="id" id="id">
                            <button type="submit" id="save-forms_submit-btn" class="btn btn-info btn-sm">{{ trans('save') }}</button>
                        </div>
                    </div> -->
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $('#save-forms_submit-btn').on('click', function(){
        var email = $.trim($('#full_name').val());
        if(!full_name){
            tips_message('{{ trans('validate.correct') }}');
            return false;
        }

        $('#save-forms_submit-form').submit();
    });
</script>