<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="HTML-CSS" />
    <meta name="og:description" content="nội dung hiển thị khi share" />
    <meta property="og:image" itemprop="thumbnailUrl" content="link hình share"/>
    <link rel="canonical" href="#" />
    <meta property="og:url" content="#" />
    <!--Favicon-->
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
    <link rel="icon" href="{{ siteIcon }}" type="image/x-icon">
    <!-- core -->
    <link href="/frontend/css/styles.css?v={{ assetsVersion }}" rel="stylesheet">
    <link href="/frontend/css/jquery-ui.min.css?v={{ assetsVersion }}" rel="stylesheet">
    <link href="/frontend/bootstrap/css/bootstrap.min.css?v={{ assetsVersion }}" rel="stylesheet">
     <link href="/frontend/css/owl.carousel.css?v={{ assetsVersion }}" rel="stylesheet">
    <!--JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js?v={{ assetsVersion }}"></script>
    <title>{{ siteTitle }}</title>
</head>