<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('widget-page/index') }}">{{ trans('label.widget-page-management') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('widget-page/index') }}">{{ trans('label.widget-page-management') }}</a>
            <small>
                <i class="icon-double-angle-right"></i>
                {{ trans('list') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12">
                <div class="btn-panel">
                    <a href="{{ url('widget-page/write') }}" class="btn btn-success btn-sm" role="button">{{ trans('label.edit') }}</a>
                    <a href="{{ url('widget-page/import') }}" class="btn btn-success btn-sm" role="button">{{ trans('label.import') }}</a>
                </div>
            </div>
        </div>
        <div class="row" style="overflow: auto;">
            <table class="table tree-grid table-striped table-bordered table-condensed table-hover" id="test-table">
                <thead>
                    {% if pages is not empty %}
                        <tr>
                            <th></th>
                            {% for page in pages %}
                                <th>{{ page.name }}</th>
                            {% endfor %}
                        </tr>
                    {% endif %}
                    </thead>
                    {% if widgets is not empty %}
                        <tbody>
                            {% for widget in widgets %}
                                <tr>
                                    <th>
                                        {{ widget.name }}
                                    </th>
                                    {% for page in pages %}
                                        <td>
                                            <div class="checkbox">
                                                <label>
                                                    {% if widgets_pages[widget.id][page.id] is not empty %}
                                                        <span class="label label-success label-white middle">X</span>
                                                    {% endif %}
                                                    <span class="lbl"></span>
                                                </label>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    {% else %}
                        <tbody>
                            <tr>
                                <td colspan="5">{{ trans('label.no-data') }}</td>
                            </tr>
                        </tbody>
                    {% endif %}
            </table>
        </div>
    </div>
</div>
