<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('widget-page/index') }}">{{ trans('label.widget-page-management') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('widget-page/index') }}">{{ trans('label.widget-page-management') }}</a>
            <small>
                <i class="icon-double-angle-right"></i>
                {{ trans('info-change') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#users" data-toggle="tab">{{ trans('label.widget-page') }}</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" style="overflow: auto;">
                <form action="{{ url('widget-page/pushlish') }}" method="post" class="form-horizontal" id="save-access-form">
                    <table class="table tree-grid table-striped table-bordered table-condensed table-hover" id="test-table">
                        <thead>
                        {% if pages is not empty %}
                            <tr>
                                <th></th>
                                {% for page in pages %}
                                    <th>{{ page.name }}</th>
                                {% endfor %}
                            </tr>
                        {% endif %}
                        </thead>
                        {% if widgets is not empty %}
                            <tbody>
                                {% for widget in widgets %}
                                    <tr>
                                        <th>
                                            {{ widget.name }}
                                        </th>
                                        {% for page in pages %}
                                            <td>
                                                <div class="checkbox">
                                                    <label>
                                                        <input name="page_widget[{{ widget.id }}][{{ page.id }}]" type="checkbox" class="ace" value="1"  {% if widgets_pages[widget.id][page.id] is not empty %}checked{% endif %}/>
                                                        <span class="lbl"></span>
                                                    </label>
                                                </div>
                                            </td>
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        {% else %}
                            <tbody>
                                <tr>
                                    <td colspan="5">{{ trans('label.no-data') }}</td>
                                </tr>
                            </tbody>
                        {% endif %}
                    </table>
                    <div class="form-group">
                        <div class="col-sm-5">
                            <button type="submit" class="btn btn-info btn-sm" data-status="1" id="save-access-btn">{{ trans('label.save') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
