<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('forms/forms') }}">{{ trans('forms') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('categorys/index') }}">{{ trans('forms') }}</a>
            <small>
                <i class="icon-double-angle-right"></i>
                {{ trans('info-change') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#forms" data-toggle="tab">{{ trans('forms') }}</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" id="forms">
                <form action="{{url('forms/publish')}}" method="post" class="form-horizontal" id="save-forms-form">
                    <div class="form-group">
                        <label for="short_code" class="col-sm-2 control-label">{{ trans('label.short_code') }}</label>
                        <div class="col-sm-5">
                            <input type="text" {% if forms is not empty %}value="{{forms['short_code']}}" readonly="" {% endif %} class="form-control" id="short_code" name="short_code">
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="realname" class="col-sm-2 control-label">{{ trans('label.html') }}</label>
                        <div class="col-sm-9">
                            <textarea class="tinymce" id="html" name="html">{% if forms is not empty %}{{forms['html']}}{% endif %}</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="archive-name" class="col-sm-2 control-label">{{ trans('label.status') }}</label>
                        <div class="controls col-xs-12 col-sm-9">
                            <div class="row">
                                <div class="col-xs-3">
                                    <label>
                                        <input name="status" class="ace ace-switch ace-switch-4 btn-flat" type="checkbox" value="1" {% if forms.status is not empty and forms.status == 1 %}checked="checked"{% endif %} />
                                        <span class="lbl"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-5">
                            <input type="hidden" {% if forms.id is not empty %} value="{{forms.id}}" {% endif %} class="form-control" name="id" id="id">
                            <button type="submit" id="save-forms-btn" class="btn btn-info btn-sm">{{ trans('save') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('#save-forms-btn').on('click', function(){
        var email = $.trim($('#short_code').val());
        if(!short_code){
            tips_message('{{ trans('validate.correct') }}');
            return false;
        }

        $('#save-forms-form').submit();
    });
</script>