<div class="main-content container">
    <!--Start content left -->
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-9 content">
                {% if articlesTopFirst is not empty %}
                <div class="row">
                    <div class="col-md-6 news-main">
                        <div class="row">
                            <a href="{{ get_url(articlesTopFirst['slug']~','~articlesTopFirst['id']) }}">
                                <img src="{{ articlesTopFirst['image'] }}" alt="hình" width="100%"/>
                            </a>
                            <a href="{{ get_url(articlesTopFirst['slug']~','~articlesTopFirst['id']) }}">
                                <h3>{{ articlesTopFirst['title'] }}</h3>
                            </a>
                            <p>{{ articlesTopFirst['introduce'] }}</p>
                        </div>
                    </div>
                    <div class="col-md-6 title-mobile">
                        <div class="row">
                            {% for article in articlesTopSecond %}
                            <div class="col-md-12 margin-bottom">
                                <div class="row">
                                    <div class="col-md-4 col-xs-4">
                                        <a href="{{ get_url(article['slug']~','~article['id']) }}">
                                            <img src="{{ article['image'] }}" alt="hình" width="100%"/>
                                        </a>
                                    </div>
                                        <p class="col-md-8 col-xs-8 padding-left0"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></p>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="col-md-12 margin-bottom">
                                <ul class="ulpadding-left15">
                                {% for article in articlesTopThird %}
                                    <li class="bottom10"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- Tin tức quảng cáo loại 1 -->
                {% if advertisesHCOne_one['html'] is not empty %}
                <div class="row margin-bottom padding100100 border-bottom border-top">
                    {{ advertisesHCOne_one['html'] }}
                </div>
                {% endif %}
                <!--End Tin tức quảng cáo loại 1 -->
                <!-- Tab Tin tức | video | hình ảnh-->
                <!-- Nav tabs -->
                {% if articlesType is not empty %}
                <div class="row margin-bottom">
                    <ul class="nav nav-tabs" role="tablist">
                        {% for index, category in articlesType %}
                            <li role="presentation" class="{% if index == 0 %} active {% endif %}"><a href="#tab{{ category['slug'] }}" aria-controls="tab{{ category['slug'] }}" role="tab" data-toggle="tab">{{ category['name'] }}</a></li>
                        {% endfor %}
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                    {% for index, category in articlesType %}
                        {% if category['id'] == 1 %}
                            {% set router = "news" %}
                        {% elseif category['id'] == 2 %}
                            {% set router = "video" %}
                        {% else %}
                            {% set router = "image" %}
                        {% endif %}
                        <div role="tabpanel" class="tab-pane {% if index == 0 %} active {% endif %}" id="tab{{ category['slug'] }}">
                            {% for article in category['articles'] %}
                                <div class="col-md-4 news-tab" style="width: 242.5px; height: 245px;">
                                    <a href="{{ get_url(article['slug']~','~article['id']~','~router) }}">
                                        <img src="{{ article['image'] }}" alt="{{ article['title'] }}" width="100%" style="max-width: 212px; max-height: 133px;" />
                                    </a>
                                    <p class="title"><a href="{{ get_url(article['slug']~','~article['id']~','~router) }}">{{ article['title'] }}</a></p>
                                    <p>{{ article['create_time'] }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    </div>
                </div>
                {% endif %}
                <!-- End tab -->
                <!-- Start tin tức quảng cáo loại 2 -->
                {% if advertisesHCTwo['html'] is not empty %}
                    <div class="row margin-bottom padding100100 border-bottom border-top">
                        {{ advertisesHCTwo['html'] }}
                    </div>
                {% endif %}
                <!-- End Tin tức quảng cáo loại 2 -->
                <!-- Catelory News danh mục tin tức -->
                {% if articlesCategoriesOnelOne is not empty and articlesCategoriesOnelTwo is not empty %}
                <div class="row margin-bottom catelory_news">
                    <div class="row">
                        <!-- block 1 -->
                        <div class="col-md-6 margin-bottom-mobile-10">
                            <ul class="nav nav-tabs" role="tablist">
                            {% for index, category in articlesCategoriesOnelOne %}
                                <li role="presentation" class="{% if index == 0 %} active {% endif %}"><a href="#block1_{{ category['id'] }}" aria-controls="block1_{{ category['id'] }}" role="tab" data-toggle="tab">{{ category['name'] }}</a></li>
                            {% endfor %}
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                            {% for index, category in articlesCategoriesOnelOne %}
                                <div role="tabpanel" class="tab-pane {% if index == 0 %} active {% endif %}" id="block1_{{ category['id'] }}">
                                    <div class="col-md-12 news-tab">
                                        <a href="{{ get_url(article['slug']~','~article['id']) }}">
                                            <img src="{{ category['articles'][0]['image'] }}" alt="{{ category['articles'][0]['title'] }}" width="100%" style="max-width: 319px; max-height: 200px;" />
                                        </a>
                                        <p class="title"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ category['articles'][0]['title'] }}</a></p>
                                        <ul class="ulpadding-left15">
                                        {% for index, article in category['articles'] %}
                                            {% if index != 0 %}
                                                <li><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                        <!-- End block 1 -->
                        <!-- block 2 -->
                        <div class="col-md-6 margin-bottom-mobile-10">
                            <ul class="nav nav-tabs" role="tablist">
                            {% for index, category in articlesCategoriesOnelTwo %}
                                <li role="presentation" class="{% if index == 0 %} active {% endif %}"><a href="#block2_{{ category['id'] }}" aria-controls="block2_{{ category['id'] }}" role="tab" data-toggle="tab">{{ category['name'] }}</a></li>
                            {% endfor %}
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                            {% for index, category in articlesCategoriesOnelTwo %}
                                <div role="tabpanel" class="tab-pane {% if index == 0 %} active {% endif %}" id="block2_{{ category['id'] }}">
                                    <div class="col-md-12 news-tab">
                                        <a href="{{ get_url(article['slug']~','~article['id']) }}">
                                            <img src="{{ category['articles'][0]['image'] }}" alt="{{ category['articles'][0]['title'] }}" width="100%" style="max-width: 319px; max-height: 200px;" />
                                        </a>
                                        <p class="title"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ category['articles'][0]['title'] }}</a></p>
                                        <ul class="ulpadding-left15">
                                        {% for index, article in category['articles'] %}
                                            {% if index != 0 %}
                                                <li><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                        <!-- End block 2 -->
                    </div>
                </div>
                {% endif %}
                <!-- End Catelory News danh mục tin tức -->
                <!-- Start tin tức quảng cáo loại 1 -->
                {% if advertisesHCOne_two['html'] is not empty %}
                <div class="row margin-bottom padding100100 border-bottom border-top">
                    {{ advertisesHCOne_two['html'] }}
                </div>
                {% endif %}
                <!--End Tin tức quảng cáo loại 1 -->
                <!-- Sidershow -->
                {% if articlesCategoryImage is not empty %}
                <div class="row margin-bottom">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            {% for index, article in articlesCategoryImage %}
                            <li data-target="#carousel-example-generic" data-slide-to="{{ index }}" {% if index == 0 %} class="active" {% endif %}></li>
                            {% endfor %}
                        </ol>
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            {% for index, article in articlesCategoryImage %}
                            <div class="item {% if index == 0 %} active {% endif %}">
                                <img src="{{ article['image'] }}" alt="{{ article['title'] }}" width="100%">
                                <div class="carousel-caption">
                                    <a href="{{ get_url(article['slug']~','~article['id']~',article') }}">
                                        {{ article['title'] }}
                                    </a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                {% endif %}
                <!-- End Sidershow -->
                <!-- Start tin tức quảng cáo loại 1 -->
                {% if advertisesHCOne_three['html'] is not empty %}
                <div class="row margin-bottom padding100100 border-bottom border-top">
                    {{ advertisesHCOne_three['html'] }}
                </div>
                {% endif %}
                <!--End Tin tức quảng cáo loại 1 -->
                <!-- Catelory News danh mục tin tức 2-->
                {% if articlesCategoriesTwolOne is not empty and articlesCategoriesTwolTwo is not empty %}
                <div class="row margin-bottom catelory_news_2">
                    <div class="row">
                        <!-- block 1 -->
                        <div class="col-md-6 margin-bottom-mobile-10">
                            <ul class="nav nav-tabs" role="tablist">
                            {% for index, category in articlesCategoriesTwolOne %}
                                <li role="presentation" class="{% if index == 0 %} active {% endif %}"><a href="#block1_{{ category['id'] }}" aria-controls="block1_{{ category['id'] }}" role="tab" data-toggle="tab">{{ category['name'] }}</a></li>
                            {% endfor %}
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                            {% for index, category in articlesCategoriesTwolOne %}
                                <div role="tabpanel" class="tab-pane {% if index == 0 %} active {% endif %}" id="block1_{{ category['id'] }}">
                                    <div class="col-md-12 news-tab">
                                        <a href="{{ get_url(article['slug']~','~article['id']) }}">
                                            <img src="{{ category['articles'][0]['image'] }}" alt="{{ category['articles'][0]['title'] }}" width="100%" style="max-width: 319px; max-height: 200px;" />
                                        </a>
                                        <p class="title"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ category['articles'][0]['title'] }}</a></p>
                                        <ul class="ulpadding-left15">
                                        {% for index, article in category['articles'] %}
                                            {% if index != 0 %}
                                                <li><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                        <!-- End block 1 -->
                        <!-- block 2 -->
                        <div class="col-md-6 margin-bottom-mobile-10">
                            <ul class="nav nav-tabs" role="tablist">
                            {% for index, category in articlesCategoriesTwolTwo %}
                                <li role="presentation" class="{% if index == 0 %} active {% endif %}"><a href="#block2_{{ category['id'] }}" aria-controls="block2_{{ category['id'] }}" role="tab" data-toggle="tab">{{ category['name'] }}</a></li>
                            {% endfor %}
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                            {% for index, category in articlesCategoriesTwolTwo %}
                                <div role="tabpanel" class="tab-pane {% if index == 0 %} active {% endif %}" id="block2_{{ category['id'] }}">
                                    <div class="col-md-12 news-tab">
                                        <a href="{{ get_url(article['slug']~','~article['id']) }}">
                                            <img src="{{ category['articles'][0]['image'] }}" alt="{{ category['articles'][0]['title'] }}" width="100%" style="max-width: 319px; max-height: 200px;" />
                                        </a>
                                        <p class="title"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ category['articles'][0]['title'] }}</a></p>
                                        <ul class="ulpadding-left15">
                                        {% for index, article in category['articles'] %}
                                            {% if index != 0 %}
                                                <li><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                        <!-- End block 2 -->
                    </div>
                </div>
                {% endif %}
                <!-- End Catelory News danh mục tin tức 2-->
                <!-- Tin mới -->
                {% if articlesNew is not empty %}
                <div class="row">
                    {% for article in articlesNew%}
                    <div class="col-md-12 margin-bottom padding0 border-bottom">
                        <div class="col-md-3 col-xs-12 padding0">
                            <a href="{{ get_url(article['slug']~','~article['id']) }}">
                                <img src="{{ article['image'] }}" alt="{{ article['title'] }}" width="100%">
                            </a>
                        </div>
                        <p class="col-md-9 col-xs-12 title title-mobile"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></p>
                        <p class="col-md-9 col-xs-12 padding-mobile-0">{{ article['create_time'] }}</p>
                        <p class="col-md-9 col-xs-12 padding-mobile-0">{{ article['introduce'] }}</p>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                <!-- End tin mới -->
            </div>
            <!--End content left -->
            <!--Start content right -->
            <aside class="col-md-3 padding-right0 padding-mobileleft0">
                {% if bannerHROne is not empty %}
                <div class="margin-bottom row">
                    {% if bannerHROne['banner'] is not empty %}
                        <div class="banner col-md-12">
                            <a href="{{ bannerHROne['url'] }}">
                                <img src="{{ bannerHROne['banner'] }}" alt="{{ bannerHROne['name'] }}" width="100%"/>
                            </a>
                        </div>
                    {% else %}
                        <div class="banner col-md-12">
                            {{ bannerHROne['html'] }}
                        </div>
                    {% endif %}
                </div>
                {% endif %}
                <!--Start danh mục right 1 -->
                {% if articlesCategoryOne is not empty %}
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="yellow">{{ articlesCategoryOne['name'] }}</h4>
                    </div>
                </div>
                <div class="catelory-right row">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-4 col-xs-12 padding0">
                                    <a href="{{ get_url(articlesCategoryOnefirst['slug']~','~articlesCategoryOnefirst['id']) }}">
                                        <img src="{{ articlesCategoryOnefirst['image'] }}" alt="{{ articlesCategoryOnefirst['title'] }}" width="100%">
                                    </a>
                                </div>
                                <p class="col-md-8 col-xs-12 title-nopadding title-mobile"><a href="{{ get_url(articlesCategoryOnefirst['slug']~','~articlesCategoryOnefirst['id']) }}">{{ articlesCategoryOnefirst['title'] }}</a></p>
                                <p class="col-md-12 col-xs-12 margin0 padding0 padding-bottom10">{{ articlesCategoryOnefirst['introduce'] }}</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <ul class="ulpadding-left15">
                                    {% for article in articlesCategoryOne['articles'] %}
                                    <li class="bottom10"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                    {% endfor%}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!--End danh mục right 1-->
                <!--Start Banner home right 2-->
                {% if bannerHRTwo is not empty %}
                <div class="margin-bottom row">
                    {% if bannerHRTwo['banner'] is not empty %}
                        <div class="banner col-md-12">
                            <a href="{{ bannerHRTwo['url'] }}">
                                <img src="{{ bannerHRTwo['banner'] }}" alt="{{ bannerHRTwo['name'] }}" width="100%"/>
                            </a>
                        </div>
                    {% else %}
                        <div class="banner col-md-12">
                            {{ bannerHRTwo['html'] }}
                        </div>
                    {% endif %}
                </div>
                {% endif %}
                <!--End Banner home right 2-->
                <!--Start Banner home right 3-->
                {% if bannerHRThree is not empty %}
                <div class="margin-bottom row">
                    {% if bannerHRThree['banner'] is not empty %}
                        <div class="banner col-md-12">
                            <a href="{{ bannerHRThree['url'] }}">
                                <img src="{{ bannerHRThree['banner'] }}" alt="{{ bannerHRThree['name'] }}" width="100%"/>
                            </a>
                        </div>
                    {% else %}
                        <div class="banner col-md-12">
                            {{ bannerHRThree['html'] }}
                        </div>
                    {% endif %}
                </div>
                {% endif %}
                <!--End Banner home right 3-->
                <!--Start danh mục right 2-->
                {% if articlesCategoryTwo is not empty %}
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="yellow">{{ articlesCategoryTwo['name'] }}</h4>
                    </div>
                </div>
                <div class="catelory-right row">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-4 col-xs-12 padding0">
                                    <a href="{{ get_url(articlesCategoryTwofirst['slug']~','~articlesCategoryTwofirst['id']) }}">
                                        <img src="{{ articlesCategoryTwofirst['image'] }}" alt="{{ articlesCategoryTwofirst['title'] }}" width="100%">
                                    </a>
                                </div>
                                <p class="col-md-8 col-xs-12 title-nopadding title-mobile"><a href="{{ get_url(articlesCategoryTwofirst['slug']~','~articlesCategoryTwofirst['id']) }}">{{ articlesCategoryTwofirst['title'] }}</a></p>
                                <p class="col-md-12 col-xs-12 margin0 padding0 padding-bottom10">{{ articlesCategoryTwofirst['introduce'] }}</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <ul class="ulpadding-left15">
                                    {% for article in articlesCategoryTwo['articles'] %}
                                    <li class="bottom10"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                    {% endfor%}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!--End danh mục right 2-->
                <!--Start banner home right 4-->
                {% if bannerHRFour is not empty %}
                <div class="margin-bottom row">
                    {% if bannerHRFour['banner'] is not empty %}
                        <div class="banner col-md-12">
                            <a href="{{ bannerHRFour['url'] }}">
                                <img src="{{ bannerHRFour['banner'] }}" alt="{{ bannerHRFour['name'] }}" width="100%"/>
                            </a>
                        </div>
                    {% else %}
                        <div class="banner col-md-12">
                            {{ bannerHRFour['html'] }}
                        </div>
                    {% endif %}
                </div>
                {% endif %}
                <!--End banner home right 4-->
                {% if bannerHRFive is not empty %}
                <div class="margin-bottom row">
                    {% if bannerHRFive['banner'] is not empty %}
                        <div class="banner col-md-12">
                            <a href="{{ bannerHRFive['url'] }}">
                                <img src="{{ bannerHRFive['banner'] }}" alt="{{ bannerHRFive['name'] }}" width="100%"/>
                            </a>
                        </div>
                    {% else %}
                        <div class="banner col-md-12">
                            {{ bannerHRFive['html'] }}
                        </div>
                    {% endif %}
                </div>
                {% endif %}
                <!--End banner home right 4-->
                <!--Start tin nổi bất-->
                {% if articlesMark is not empty %}
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="yellow">Tin nổi bật</h4>
                    </div>
                </div>
                <div class="news-nb row">
                    {% for article in articlesMark %}
                    <div class="col-md-12">
                        <div class="col-md-12 margin-bottom">
                            <div class="row">
                                <div class="col-md-4 col-xs-12 padding0">
                                    <a href="{{ get_url(article['slug']~','~article['id']) }}">
                                        <img src="{{ article['image'] }}" alt="{{ article['title'] }}" width="100%">
                                    </a>
                                </div>
                                <p class="col-md-8 col-xs-12 title-mobile"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                <!--End tin nổi bất-->
                <!--Start danh mục right 3-->
                {% if articlesCategoryThree is not empty %}
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="yellow">{{ articlesCategoryThree['name'] }}</h4>
                    </div>
                </div>
                <div class="catelory-right row">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-4 col-xs-12 padding0">
                                    <a href="{{ get_url(articlesCategoryThreefirst['slug']~','~articlesCategoryThreefirst['id']) }}">
                                        <img src="{{ articlesCategoryThreefirst['image'] }}" alt="{{ articlesCategoryThreefirst['title'] }}" width="100%">
                                    </a>
                                </div>
                                <p class="col-md-8 col-xs-12 title-nopadding title-mobile"><a href="{{ get_url(articlesCategoryThreefirst['slug']~','~articlesCategoryThreefirst['id']) }}">{{ articlesCategoryThreefirst['title'] }}</a></p>
                                <p class="col-md-12 col-xs-12 margin0 padding0 padding-bottom10">{{ articlesCategoryThreefirst['introduce'] }}</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <ul class="ulpadding-left15">
                                    {% for article in articlesCategoryThree['articles'] %}
                                    <li class="bottom10"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                    {% endfor%}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!--End danh mục right 3-->
                <!--Start danh mục right 4-->
                {% if articlesCategoryFour is not empty %}
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="yellow">{{ articlesCategoryFour['name'] }}</h4>
                    </div>
                </div>
                <div class="catelory-right row">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-4 col-xs-12 padding0">
                                    <a href="{{ get_url(articlesCategoryFourfirst['slug']~','~article['id']) }}">
                                        <img src="{{ articlesCategoryFourfirst['image'] }}" alt="{{ articlesCategoryFourfirst['title'] }}" width="100%">
                                    </a>
                                </div>
                                <p class="col-md-8 col-xs-12 title-nopadding title-mobile"><a href="{{ get_url(articlesCategoryFourfirst['slug']~','~article['id']) }}">{{ articlesCategoryFourfirst['title'] }}</a></p>
                                <p class="col-md-12 col-xs-12 margin0 padding0 padding-bottom10">{{ articlesCategoryFourfirst['introduce'] }}</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <ul class="ulpadding-left15">
                                    {% for article in articlesCategoryFour['articles'] %}
                                    <li class="bottom10"><a href="{{ get_url(article['slug']~','~article['id']) }}">{{ article['title'] }}</a></li>
                                    {% endfor%}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!--End danh mục right 4-->
                {% if bannerHRSix is not empty %}
                <div class="margin-bottom row">
                    {% if bannerHRSix['banner'] is not empty %}
                        <div class="banner col-md-12">
                            <a href="{{ bannerHRSix['url'] }}">
                                <img src="{{ bannerHRSix['banner'] }}" alt="{{ bannerHRSix['name'] }}" width="100%"/>
                            </a>
                        </div>
                    {% else %}
                        <div class="banner col-md-12">
                            {{ bannerHRSix['html'] }}
                        </div>
                    {% endif %}
                </div>
                {% endif %}
            </aside>
            <!--End content right -->
        </div>
    </div>
</div>
<!-- Start tin tức quảng cáo loại 3 -->
{% if advertisesHCThree is not empty %}
    {{ advertisesHCThree['html'] }}
{% endif %}
<!-- End Tin tức quảng cáo loại 3 -->
<!-- Start tin tức quảng cáo loại 4 -->
{% if advertisesHCFour is not empty %}
    {{ advertisesHCFour['html'] }}
{% endif %}
<!-- End Tin tức quảng cáo loại 4 -->