<meta charset="utf-8" />
<title>{{title}}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="{{ static_url('bootstrap/css/bootstrap.min.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ static_url('ace/css/font-awesome.min.css?_v=')~assetsVersion }}" />
<link rel="stylesheet" href="{{ static_url('ace/font-awesome/4.5.0/css/font-awesome.min.css?_v=')~assetsVersion }}" />
<link href="{{ static_url('assets/css/style.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ static_url('ace/css/ace.min.css?_v=')~assetsVersion }}" />

<script src="{{ static_url('ace/js/jquery-2.0.3.min.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('bootstrap/js/bootstrap.min.js?_v=')~assetsVersion }}"></script>
<!-- <script src="{{ static_url('ace/js/ace-extra.min.js?_v=')~assetsVersion }}"></script> -->

<script src="{{ static_url('ace/js/ace.min.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('treegrid/js/jquery.treegrid.js?_v=')~assetsVersion }}"></script>
<!-- <script src="{{ static_url('ace/js/ace-elements.min.js?_v=')~assetsVersion }}"></script> -->
<script src="{{ static_url('assets/js/public.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('tinymce/tinymce.min.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript" src="{{ static_url('assets/js/master.js?_v=')~assetsVersion }}"></script>
